### ISSUE TITLE
WebGL question

### ISSUE THREAD

**Issue by AlexanderKozhevin** [derjanb/hamiyoca#19]
There are 3 options right now.
1) casual way
2) Web-workers
3) Web-GL
In first case I got ~1000 hashes/s
In second case about 100'000 hashes /s
**In third I saw 1000 hashes/s** 
Should I multiple this number by 1024 threads? which results about a million hashes/s.

Or it's smth wrong with my macbook and 1000 hashes/s with WebGL is total value?
Cause if it's true, it means that Web-Workers are dozens of times faster than WebGL.
But web-workers are running on CPU, while WebGL use GPU.

**Comment by 796F** [comment]
@AlexanderKozhevin unfortunately WebGL is slower because of the time latency for loading and reading data into textures.  

while the processing is theoretically faster, WebGL has many bottlenecks that make it unfit for mining :(

**Comment by AlexanderKozhevin** [comment]
@xiamike Thank you for information.
