### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by ganzuul** [derjanb/hamiyoca#2]
Need to lobby the browser vendors to add an icon for WebGL the same way tabs making noise get a little speaker...

**Comment by therealxooxlor** [comment]
He should have the favicon change so their is a bitcoin in the corner of it. I don't know about auto image editing but grab favicon.ico and edited it with php maybe?

**Comment by derjanb** [comment]
> Need to lobby the browser vendors to add an icon for WebGL the same way tabs making noise get a little speaker...

Good idea.
