### ISSUE TITLE
Stop polling!!!! 

### ISSUE THREAD

**Issue by sebastien247** [derjanb/hamiyoca#3]
Le script ne fonctionne pas pour moi :

Stop polling!!!!               work-manager.js:125

J'ai testé le script sur 2 serveurs différents, mais j'obtient le même résultat a chaque fois.

-----------------------------------------------
The script does not work for me :

Stop polling!!!! work-manager.js:125

I tested the script on two different servers, but I get the same result every time.

**Comment by derjanb** [comment]
Fixed by 0369cff48dc2ba641d67164c8d0d4d00c6970bfb
