### ISSUE TITLE
How to use a specified mining pool?

### ISSUE THREAD

**Issue by JDok** [derjanb/hamiyoca#4]
Hi, 

I try to use hamiyoca to mine bitcoins with my friends on ghash.io or bitcoin.cz . 
If I put the direct url and data to the mining pool in credentials.class.php it doesnt work.

I also tried to use https://github.com/slush0/stratum-mining-proxy with following data in
credentials.class.php:
 $url = "localhost";
 $port = "8332";
 $username = "TBone.worker1";
 $password = "...";

For stratum-mining-proxy I use following options:
--host stratum.bitcoin.cz --port 3333

stratum-mining-proxy can connect to the mining pool and doesnt throw any errors.
It shows that there are new jobs and shares are submitted. 
But it doesnt work too. (No data on mining pool)

I dont know if there is a problem with the data from the hamiyoca script or
if there is a problem with the communictaion between client side - stratum proxy - mining pool.

Does anyone know how to do it right?
What is the problem? 

Hope someone can help me.
Thanks and have a nice day

**Comment by derjanb** [comment]
Stratum is not supported.

Fixed by 0369cff48dc2ba641d67164c8d0d4d00c6970bfb
