### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by DavidAwad** [derjanb/hamiyoca#6]
Exactly that, the readme is completely blank.

**Comment by DavidAwad** [comment]
Any information at all : ( I still want to learn this.

**Comment by therealxooxlor** [comment]
I think in cred.class.php you need to supply a pool. I believe it doesnt support stratum creator kinda abandonded this for many reasons.

**Comment by DavidAwad** [comment]
Yeah I ended up forking it to write docs and just figure it out myself.

**Comment by derjanb** [comment]
Fixed by 0369cff48dc2ba641d67164c8d0d4d00c6970bfb
