### ISSUE TITLE
Please add Bitcoin as a donation option -- put it as the first option by default

### ISSUE THREAD

**Issue by greatwolf** [derjanb/hamiyoca#7]
I was looking at donating to Tampermonkey but was dismayed at the available options. Please make it easier to donate by putting Bitcoin as the *first* option under the Contribute/Donation page.

Thanks

**Comment by DavidAwad** [comment]
Do you know how to use this ?? Could you write some Docs as I really want to try using it but don't have the time to really dig through it just to get it running.

**Comment by greatwolf** [comment]
Do you mean how to get a bitcoin address? You mainly need to get a bitcoin wallet setup and it automatically generates a bitcoin address which you can copy and paste into the Contribution page. You can also include a QR code that encodes that address to make it easier to pay with a smart device.

There are many bitcoin wallets out there with differing models of security, features and ease of use. Airbitz is a good mobile wallet for Android and iOS -- it has a nice decentralized architecture while you maintain control the private keys. If you're on an iPhone, breadwallet is another popular one.

For web wallets, there's Copay and Greenaddress. For desktop clients, there's bitcoin-qt core and electrum.

Hope that helps

**Comment by DavidAwad** [comment]
No no, I mean how to run hamiyoca. It doesn't come with any information.

**Comment by greatwolf** [comment]
wait, nm. I didn't notice I posted this under hamiyoca's repo, I meant to post this issue under https://github.com/derjanb/tampermonkey/issues

ignore this issue.
