### ISSUE TITLE
change url and port

### ISSUE THREAD

**Issue by amir-b7** [derjanb/hamiyoca#8]
Hi.Should I change url and port in credentials.class.php?
I want use this script in a online site that everyone open the page help the mining?
what should i change for that?
tnx

**Comment by BrainyBrian** [comment]
Change to URL to that of the mining pool

**Comment by BrainyBrian** [comment]
And by the way this dosent work with chrome due to some sort of cross-site scripting confusion, you cannot put this online without having a getwork pool on the same server, that probably is a subpool of some other pool, or fix the XSS confusion

**Comment by SherlockStd** [comment]
Working on Chrome ^^
